tuple_transform_each(): Attempt to take a template template parameter.
For the tranformer, so that we an call transform<element_type>::tranform(element).
However, this template specialization now doesn't compile:

template<template<typename> class T_transformer, std::size_t index>
struct tuple_transform_each_impl<T_transformer, 0>

clang++ says:

./tuple-utils/tuple_transform_each.h:57:8: error: class template partial specialization contains a template parameter that cannot be deduced; this
      partial specialization will never be used [-Werror]
struct tuple_transform_each_impl<T_transformer, 0>
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tuple-utils/tuple_transform_each.h:56:62: note: non-deducible template parameter 'index'
template<template<typename> class T_transformer, std::size_t index>